# this file is just an example

settings:
  timeout: 0.5 # timeout between jobs (seconds)

jobs:
  git-branch: # job_name
    run: # commands list
      - git branch # actual command
  flake8-lint:
    required: False # if not required, the pre-commit will continue to work regardless of the error
    run:
      - flake8 --version
      - flake8 ./test.py
  python-tests:
    required: True
    run:
      - python -m unittest ./test.py -q
