[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "prepy"
authors = [{ name = "Lev Zlobin", email = "lengthylyova@gmail.com" }]
dependencies = ["PyYAML >= 6.0.2"]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/lengthylyova/prepy"
Issues = "https://github.com/lengthylyova/issues"

[project.scripts]
prepy = "prepy.entrypoints:prepy"

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = { attr = "prepy.__version__" }