settings:
  timeout: 0.5 # timeout between jobs (seconds)

jobs:
  greeting: # job_name
    with: {{scripts}} # scripts list to use this job
    quite: False # nugit ignores job output if True (default=False) and no error occurred
    required: True # is successful completion required?
    run: # commands list
      - echo "Hi from Nugit!" # actual command